language: node_js
node_js:
  - "0.10"
  - 6
  - 7
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: intern-example-ci
    - SAUCE_ACCESS_KEY: a4eb8d67-ef84-444e-a436-b588abb7faef
install:
  - cd travis-ci-example
  - npm install
script: npm test
